import { z } from 'zod';

export const POSITIONS_QUEUE_NAME = 'positions-ingest';

const latSchema = z.number().min(-90).max(90);
const lonSchema = z.number().min(-180).max(180);

/**
 * Public ingestion payload. operatorId is intentionally NOT in the body —
 * the controller derives it from the JWT (CLAUDE.md §3.7 — anti-spoofing).
 */
export const ingestPositionSchema = z.object({
  eventId: z.string().uuid(),
  lat: latSchema,
  lon: lonSchema,
  accuracyM: z.number().min(0).max(100_000).optional(),
  headingDeg: z.number().min(0).max(360).optional(),
  speedMps: z.number().min(0).max(1_000).optional(),
  /** Client-side ISO 8601 capture time. Server may override on extreme drift. */
  recordedAt: z.string().datetime(),
  /** UUID v4 generated by the mobile app for cross-reconnect dedup. */
  clientEventId: z.string().uuid(),
});

export type IngestPositionDto = z.infer<typeof ingestPositionSchema>;

/** Job payload pushed onto BullMQ — service composes it; processor consumes. */
export interface PositionIngestJob extends IngestPositionDto {
  operatorId: string;
  receivedAt: string;
}

export interface IngestAcceptedView {
  accepted: true;
  clientEventId: string;
}

/**
 * Live snapshot kept in Redis under `live:position:{operatorId}` with TTL 60s.
 * Read path (admin live-map, mobile teammates view) hits Redis only.
 */
export interface LivePositionSnapshot {
  operatorId: string;
  eventId: string;
  lat: number;
  lon: number;
  accuracyM?: number;
  headingDeg?: number;
  speedMps?: number;
  recordedAt: string;
  receivedAt: string;
}
